require 'sexp_processor'
require 'parse_tree'
require 'parse_tree_extensions'
require 'php/version'

module PHP
  autoload :Class,      'php/syntax/class'
  autoload :Comment,    'php/syntax/comment'
  autoload :Constant,   'php/syntax/constant'
  autoload :Expression, 'php/syntax/expression'
  autoload :Function,   'php/syntax/function'
  autoload :Identifier, 'php/syntax/identifier'
  autoload :Interface,  'php/syntax/interface'
  autoload :Literal,    'php/syntax/literal'
  autoload :Namespace,  'php/syntax/namespace'
  autoload :Node,       'php/syntax/node'
  autoload :Program,    'php/syntax/program'
  autoload :Statement,  'php/syntax/statement'
  autoload :Variable,   'php/syntax/variable'
end
